# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:04
from __future__ import unicode_literals

from django.db import migrations
import io


def loadInitialData(filename):
    with io.open('./hc_pacientes/migrations/initial_data/' + filename + '.sql', 'r', encoding='utf8') as file:
        return file.read()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_pacientes', '0001_initial'),
    ]

    operations = [
    #    migrations.RunSQL(loadInitialData('paciente')),
    ]
