# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hc_pacientes', '0003_paciente_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='updated_on',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 29, 17, 47, 45, 731631, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
