# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.6 on 2016-05-07 17:08
=======
# Generated by Django 1.9.1 on 2016-05-22 16:37
>>>>>>> cc6811729eb8fb7734765ba6082b3f94513b11f2
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hc_pacientes', '0001_initial'),
        ('hc_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('validFrom', models.DateField(blank=True)),
                ('validTo', models.DateField(blank=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Ausencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField(default=b'00:00:00')),
                ('end', models.TimeField(default=b'23:59:59')),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
>>>>>>> cc6811729eb8fb7734765ba6082b3f94513b11f2
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('selected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('selected', models.BooleanField()),
                ('daysOfWeek', models.ManyToManyField(to='hc_practicas.DayOfWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=150)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('default', models.NullBooleanField(default=False)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='hc_practicas.Especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_common.Persona')),
                ('prestaciones', models.ManyToManyField(to='hc_practicas.Prestacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_common.persona',),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField(default=b'08:00:00')),
                ('end', models.TimeField(default=b'17:00:00')),
                ('taken', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=7)),
>>>>>>> cc6811729eb8fb7734765ba6082b3f94513b11f2
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_pacientes.Paciente')),
                ('prestacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Prestacion')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Profesional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
<<<<<<< HEAD
=======
            model_name='ausencia',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Profesional'),
        ),
        migrations.AddField(
>>>>>>> cc6811729eb8fb7734765ba6082b3f94513b11f2
            model_name='agenda',
            name='periods',
            field=models.ManyToManyField(to='hc_practicas.Period'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='prestacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacion', to='hc_practicas.Prestacion'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='hc_practicas.Profesional'),
        ),
    ]
