# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hc_pacientes', '__first__'),
        ('hc_common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('validFrom', models.DateField(blank=True)),
                ('validTo', models.DateField(blank=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(default=django.utils.timezone.now)),
                ('end_day', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('selected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('selected', models.BooleanField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='hc_practicas.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('default', models.BooleanField(default=False)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='hc_practicas.Especialidad')),
            ],
            options={
                'ordering': ['-default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_common.Persona')),
                ('municipalNumber', models.CharField(max_length=8)),
                ('licenseNumber', models.CharField(max_length=8)),
                ('updated_on', models.DateField(auto_now=True)),
                ('prestaciones', models.ManyToManyField(to='hc_practicas.Prestacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_common.persona',),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('state', models.CharField(choices=[(b'Initial', b'Inicial'), (b'Present', b'Presente'), (b'Absent', b'Ausente'), (b'Served', b'Atendido'), (b'Canceled', b'Cancelado'), (b'Canceled and informed', b'Cancelado e informado')], default=b'Initial', max_length=10)),
                ('cancelation_reason', models.CharField(choices=[(b'ProfesionalAbsent', b'Ausencia del profesional'), (b'AgendaChanged', b'Cambio o baja de agenda'), (b'PacientRequest', b'Pedido del paciente'), (b'Other', b'Otro')], max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('informed', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc_pacientes.Paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField(default=b'08:00:00')),
                ('end', models.TimeField(default=b'17:00:00')),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('state', models.CharField(choices=[(b'Available', b'Disponible'), (b'Occupied', b'Ocupado'), (b'Conflict', b'En conflicto'), (b'Deleted', b'Eliminado')], max_length=10)),
                ('updated_on', models.DateField(auto_now=True)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Agenda')),
                ('prestacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Prestacion')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Profesional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='turnoSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='hc_practicas.TurnoSlot'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daysOfWeek', to='hc_practicas.Period'),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Profesional'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='prestacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestacion', to='hc_practicas.Prestacion'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='hc_practicas.Profesional'),
        ),
    ]
