# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cancelation_reason',
            field=models.CharField(choices=[(b'ProfesionalAbsent', b'Ausencia del profesional'), (b'AgendaChanged', b'Cambio o baja de agenda'), (b'PacientRequest', b'Pedido del paciente'), (b'PatientSMS', b'SMS del paciente'), (b'PatientEmail', b'Email del paciente'), (b'Other', b'Otro')], max_length=20, null=True),
        ),
    ]
