# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='status',
            field=models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8),
        ),
    ]
