# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 12, 7, 30, 928925)),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 12, 7, 30, 928885)),
        ),
    ]
