# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0002_auto_20160523_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencia',
            name='day',
        ),
        migrations.RemoveField(
            model_name='ausencia',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ausencia',
            name='start',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 11, 16, 8, 972488)),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='reason',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2016, 5, 24, 11, 16, 8, 972458)),
        ),
    ]
