# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0002_auto_20170205_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='title',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
