# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0003_auto_20160524_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='end_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
