# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0004_auto_20160603_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='licenseNumber',
            field=models.CharField(default='none', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='municipalNumber',
            field=models.CharField(default='none', max_length=8),
            preserve_default=False,
        ),
    ]
