# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0005_auto_20160611_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
