# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0007_auto_20160616_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
