# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations

def loadEspecialidades(apps, schema_editor):
    Especialidad = apps.get_model("hc_practicas", "Especialidad")

    Especialidad(
        name="Infectología",
        description="Especialidad de Infectología",
        status="Active"
        ).save()

    Especialidad(
        name="Ginecología y obstetricia",
        description="Especialidad de Ginecología y obstetricia",
        status="Active"
        ).save()

    Especialidad(
        name="Coloproctología",
        description="Especialidad de Coloproctología",
        status="Active"
        ).save()

    Especialidad(
        name="Nutrición",
        description="Especialidad de Nutrición",
        status="Active"
        ).save()

    Especialidad(
        name="Hepatología",
        description="Especialidad de Hepatología",
        status="Active"
        ).save()

    Especialidad(
        name="Pediatría",
        description="Especialidad de Pediatría",
        status="Active"
        ).save()

    Especialidad(
        name="Neurología",
        description="Especialidad de Neurología",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0008_auto_20160616_0016'),
    ]

    operations = [
        migrations.RunPython(loadEspecialidades),
    ]
