# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations


def loadEspecialidades(apps, schema_editor):
    Especialidad = apps.get_model("hc_practicas", "Especialidad")

    Especialidad(
        name="Infectología",
        description="Especialidad de Infectología",
        status="Active"
        ).save()

    Especialidad(
        name="Ginecología",
        description="Especialidad de Ginecología",
        status="Active"
        ).save()

    Especialidad(
        name="Trastornos Metabólicos",
        description="Especialidad de Trastornos Metabólicos",
        status="Active"
        ).save()

    Especialidad(
        name="Nutrición",
        description="Especialidad de Nutrición",
        status="Active"
        ).save()

    Especialidad(
        name="Dermatología",
        description="Especialidad de Dermatología",
        status="Active"
        ).save()

    Especialidad(
        name="Psiquiatría",
        description="Especialidad de Psiquiatría",
        status="Active"
        ).save()

    Especialidad(
        name="Proctología",
        description="Especialidad de Proctología",
        status="Active"
        ).save()

    Especialidad(
        name="Endocrinología",
        description="Especialidad de Endocrinología",
        status="Active"
        ).save()

    Especialidad(
        name="Psicología",
        description="Especialidad de Psicología",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0008_auto_20160616_0016'),
    ]

    operations = [
        migrations.RunPython(loadEspecialidades),
    ]
