# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations


def loadPrestaciones(apps, schema_editor):
    Especialidad = apps.get_model("hc_practicas", "Especialidad")
    Prestacion = apps.get_model("hc_practicas", "Prestacion")

    Prestacion(
        name="Primera vez - Infectología",
        description="Consulta de Primera vez - Infectología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Seguimiento - Infectología",
        description="Consulta de seguimiento - Infectología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Tuberculosis",
        description="Consulta de Tuberculosis",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="ETS - Enfermedad de trans. sexual",
        description="Enfermedad de Transmisión Sexual",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Traumatología",
        description="Consulta para traumatología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Embarazadas",
        description="Consulta para embarazadas",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Pediátricos",
        description="Consulta para pediátricos",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Micología",
        description="Consulta para micología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Pediátricos y Adolescentes",
        description="Consulta para pediátricos y adolescentes",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Hepatitis C",
        description="Consulta para hepatitis C",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Primera vez - Ginecología",
        description="Consulta de primera vez Ginecología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Ginecología")
        ).save()

    Prestacion(
        name="Seguimiento - Ginecología",
        description="Consulta de seguimiento Ginecología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Ginecología")
        ).save()

    Prestacion(
        name="Primera vez - Trastornos metabólicos",
        description="Consulta de primera vez - Trastornos metabólicos",
        duration=20,
        especialidad=Especialidad.objects.get(name="Trastornos Metabólicos")
        ).save()

    Prestacion(
        name="Seguimiento - Trastornos metabólicos",
        description="Consulta de seguimiento - Trastornos metabólicos",
        duration=20,
        especialidad=Especialidad.objects.get(name="Trastornos Metabólicos")
        ).save()

    Prestacion(
        name="Primera vez - Nutrición",
        description="Consulta de primera vez - Nutrición",
        duration=20,
        especialidad=Especialidad.objects.get(name="Nutrición")
        ).save()

    Prestacion(
        name="Seguimiento - Nutrición",
        description="Consulta de seguimiento - Nutrición",
        duration=20,
        especialidad=Especialidad.objects.get(name="Nutrición")
        ).save()

    Prestacion(
        name="Primera vez - Dermatología",
        description="Consulta de primera vez - Dermatología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Dermatología")
        ).save()

    Prestacion(
        name="Seguimiento - Dermatología",
        description="Consulta de primera vez - Dermatología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Dermatología")
        ).save()

    Prestacion(
        name="Primera vez - Psiquiatria",
        description="Consulta de primera vez - Psiquiatría",
        duration=20,
        especialidad=Especialidad.objects.get(name="Psiquiatría")
        ).save()

    Prestacion(
        name="Seguimiento - Psiquiatria",
        description="Consulta de seguimiento - Psiquiatría",
        duration=20,
        especialidad=Especialidad.objects.get(name="Psiquiatría")
        ).save()

    Prestacion(
        name="Test Cognitivo",
        description="Test Cognitivo - Psiquiatría",
        duration=20,
        especialidad=Especialidad.objects.get(name="Psiquiatría")
        ).save()

    Prestacion(
        name="Primera vez Proctología (Sólo proyecto T)",
        description="Consulta de primera vez - Proctología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Proctología")
        ).save()

    Prestacion(
        name="Seguimiento Proctología (Sólo proyecto T)",
        description="Consulta de seguimiento - Proctología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Proctología")
        ).save()

    Prestacion(
        name="Primera vez Endocrinología (Sólo proyecto T)",
        description="Consulta de primera vez - Endocrinología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Endocrinología")
        ).save()

    Prestacion(
        name="Seguimiento Endocrinología (Sólo proyecto T)",
        description="Consulta de seguimiento - Endocrinología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Endocrinología")
        ).save()

    Prestacion(
        name="Primera vez Psicologia (Sólo Adherencia)",
        description="Consulta de primera vez - Psicología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Psicología")
        ).save()

    Prestacion(
        name="Seguimiento Psicología (Sólo Adherencia)",
        description="Consulta seguimiento - Psicología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Psicología")
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0009_auto_20160616_1218'),
    ]

    operations = [
        migrations.RunPython(loadPrestaciones),
    ]
