# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations


def loadPrestaciones(apps, schema_editor):
    Especialidad = apps.get_model("hc_practicas", "Especialidad")
    Prestacion = apps.get_model("hc_practicas", "Prestacion")

    Prestacion(
        name="Primera vez - Infectología",
        description="Consulta de Primera vez - Infectología",
        duration=40,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Seguimiento - Infectología",
        description="Consulta de seguimiento - Infectología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Infectología")
        ).save()

    Prestacion(
        name="Consulta - Ginecología y obstetricia",
        description="Consulta Ginecología y obstetricia",
        duration=20,
        especialidad=Especialidad.objects.get(name="Ginecología y obstetricia")
        ).save()

    Prestacion(
        name="Consulta - Coloproctología",
        description="Consulta Coloproctología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Coloproctología")
        ).save()

    Prestacion(
        name="Consulta - Nutrición",
        description="Consulta Nutrición",
        duration=10,
        especialidad=Especialidad.objects.get(name="Nutrición")
        ).save()

    Prestacion(
        name="Consulta - Hepatología",
        description="Consulta Hepatología",
        duration=20,
        especialidad=Especialidad.objects.get(name="Hepatología")
        ).save()

    Prestacion(
        name="Consulta - Pediatría",
        description="Consulta Pediatría",
        duration=20,
        especialidad=Especialidad.objects.get(name="Pediatría")
        ).save()

    Prestacion(
        name="Consulta - Neurología",
        description="Consulta - Dermatología",
        duration=30,
        especialidad=Especialidad.objects.get(name="Neurología")
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0009_auto_20160616_1218'),
    ]

    operations = [
        migrations.RunPython(loadPrestaciones),
    ]
