# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0010_auto_20160616_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['default', 'name']},
        ),
        migrations.AlterModelOptions(
            name='prestacion',
            options={'ordering': ['default', 'name']},
        ),
        migrations.AddField(
            model_name='especialidad',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
