# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0012_auto_20160626_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='updated_on',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 29, 17, 51, 17, 916495, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='updated_on',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 29, 17, 51, 19, 380233, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='updated_on',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 29, 17, 51, 20, 788715, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
