# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0013_auto_20160629_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Agenda'),
        ),
    ]
