# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0014_turno_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='period',
            name='daysOfWeek',
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='daysOfWeek', to='hc_practicas.Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='agenda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='hc_practicas.Agenda'),
            preserve_default=False,
        ),
    ]
