# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0016_auto_20160919_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cancelation_reason',
            field=models.CharField(choices=[(b'Profesional absent', b'Ausencia del profesional'), (b'Agenda changed', b'Cambio o baja de agenda'), (b'Pacient request', b'Pedido del paciente'), (b'Other', b'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='state',
            field=models.CharField(choices=[(b'Initial', b'Inicial'), (b'Present', b'Presente'), (b'Absent', b'Ausente'), (b'Served', b'Atendido'), (b'Canceled', b'Cancelado'), (b'Canceled and informed', b'Cancelado e informado')], default=b'Initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turnoSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='hc_practicas.TurnoSlot'),
        ),
    ]
