# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old')], default='home', max_length=4)),
                ('type', models.CharField(choices=[('postal', 'Postal Address'), ('physical', 'Physical Address'), ('both', 'Physical and Postal Address')], default='both', max_length=8)),
                ('text', models.TextField()),
                ('city', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('postalCode', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressPointPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.URLField()),
                ('version', models.TextField()),
                ('code', models.TextField()),
                ('display', models.TextField()),
                ('userSelected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('pager', 'Pager'), ('fa', 'Facebook'), ('tw', 'Twitter'), ('other', 'Other')], default='mob', max_length=5)),
                ('value', models.TextField()),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('mob', 'Mobile')], default='home', max_length=4)),
                ('rank', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPointPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='HumanName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporal'), ('nickname', 'Nickname'), ('anonymous', 'Anonymous'), ('old', 'Old'), ('maiden', 'Maiden')], default='usual', max_length=9)),
                ('text', models.TextField()),
                ('family', models.TextField()),
                ('given', models.TextField()),
                ('prefix', models.TextField(null=True)),
                ('suffix', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('US', 'Usual use'), ('OF', 'Official use'), ('TE', 'Temporal use'), ('SE', 'Secondary use')], default='OF', max_length=2)),
                ('system', models.URLField()),
                ('value', models.TextField(max_length=6, unique=True)),
                ('assigner', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.CharField(max_length=4)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=9)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300, null=True)),
                ('mode', models.CharField(choices=[('instance', 'Instance'), ('kind', 'Kind')], default='instance', max_length=8)),
                ('type', models.CharField(max_length=6, null=True)),
                ('physicalType', models.CharField(choices=[('bu', 'Building'), ('wi', 'Wing'), ('lvl', 'Level'), ('co', 'Corridor'), ('ro', 'Room'), ('bd', 'Bed'), ('ve', 'Vehicle'), ('ho', 'House'), ('ca', 'Cabinet'), ('rd', 'Road'), ('jdn', 'Jurisdiction'), ('area', 'Area')], default='bu', max_length=4)),
                ('positionLongitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('positionLatitude', models.DecimalField(decimal_places=2, max_digits=3)),
                ('positionAltitude', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('address', models.ManyToManyField(to='common.Address')),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='NamePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('type', models.CharField(choices=[('PROV', 'Healthcare Provider'), ('DEPT', 'Hospital Department'), ('TEAM', 'Organizational team'), ('GOVT', 'Government'), ('INS', 'Insurance Company'), ('EDU', 'Educational Institute'), ('REL', 'Religious Institution'), ('CRS', 'Clinical Research Sponsor'), ('CG', 'Community Group'), ('BUS', 'Non-Healthcare Business or Corporation'), ('OTHER', 'Other')], default='DEPT', max_length=5)),
                ('name', models.TextField()),
                ('address', models.ManyToManyField(to='common.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('bill', 'Billing'), ('adm', 'Administrative'), ('hr', 'Human Resource'), ('pay', 'Payor'), ('pat', 'Patient'), ('pres', 'Press')], default='adm', max_length=4)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.HumanName')),
                ('telecom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ContactPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro'), ('unknown', 'Desconocido')], default='unknown', max_length=7)),
                ('birthDate', models.DateField(null=True)),
                ('photo', models.URLField(null=True)),
                ('active', models.BooleanField()),
                ('address', models.ManyToManyField(to='common.Address')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField()),
                ('assurance', models.CharField(choices=[('level1', 'Nivel 1'), ('level2', 'Nivel 2'), ('level3', 'Nivel 3'), ('level4', 'Nivel 4')], default='level1', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.ManyToManyField(to='common.PersonLink'),
        ),
        migrations.AddField(
            model_name='person',
            name='managingOrganization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Organization'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.HumanName'),
        ),
        migrations.AddField(
            model_name='person',
            name='telecom',
            field=models.ManyToManyField(to='common.ContactPoint'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ManyToManyField(to='common.OrganizationContact'),
        ),
        migrations.AddField(
            model_name='organization',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Identifier'),
        ),
        migrations.AddField(
            model_name='organization',
            name='partOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telecom',
            field=models.ManyToManyField(to='common.ContactPoint'),
        ),
        migrations.AddField(
            model_name='location',
            name='managingOrganization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='partOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='telecom',
            field=models.ManyToManyField(to='common.ContactPoint'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.IdentifierPeriod'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.IdentifierType'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.NamePeriod'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='common.ContactPointPeriod'),
        ),
        migrations.AddField(
            model_name='address',
            name='lines',
            field=models.ManyToManyField(related_name='lines', to='common.AddressLine'),
        ),
        migrations.AddField(
            model_name='address',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='common.AddressPointPeriod'),
        ),
    ]
