from .type_ser import *
from .typeNested_ser import *
from .typeNest_ser import *
from .sexType_ser import *
from .sexTypeNested_ser import *
from .province_ser import *
from .provinceNested_ser import *
from .districtNested_ser import *
from .provinceNest_ser import *
from .districtNest_ser import *
from .locationNest_ser import *
from .district_ser import *
from .location_ser import *
from .locationNested_ser import *
from .documentType_ser import *
from .documentTypeNested_ser import *
from .educationType_ser import *
from .educationTypeNested_ser import *
from .civilStatusType_ser import *
from .civilStatusTypeNested_ser import *
from .socialService_ser import *
from .socialServiceNested_ser import *
from .documentType_ser import *
from .phone_ser import *
from .phoneNest_ser import *
