from .type_ser import *
from .typeNest_ser import *
from .sexType_ser import *
from .sexTypeNest_ser import *
from .documentType_ser import *
from .documentTypeNest_ser import *
from .phoneType_ser import *
from .phoneTypeNest_ser import *
from .phoneNest_ser import *
from .civilStatusType_ser import *
from .civilStatusTypeNest_ser import *
from .socialService_ser import *
from .province_ser import *
from .provinceNest_ser import *
from .socialServiceNest_ser import *
from .educationType_ser import *
from .educationTypeNested_ser import *
from .district_ser import *
from .districtNest_ser import *
from .location_ser import *
from .locationNest_ser import *
from .address_ser import *
from .addressNest_ser import *
from .persona_ser import *
from .personaNest_ser import *
