insert into hc_common_socialservice (id, name, description, status) values (1, 'Aceros Parana', 'Aceros Parana', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (2, 'ADOS MAR DEL PLATA-Asoc de Os Mar Del Plata', 'ADOS MAR DEL PLATA-Asoc de Os Mar Del Plata', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (3, 'ADOS ROSARIO -Asoc de Os de Rosario', 'ADOS ROSARIO -Asoc de Os de Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (4, 'Agentes De Propaganda Medica de Cordoba', 'Agentes De Propaganda Medica de Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (5, 'Agentes De Propaganda Medica de Rosario', 'Agentes De Propaganda Medica de Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (6, 'Allied Domecq Arg S.A.', 'Allied Domecq Arg S.A.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (7, 'AMEB SALUD (FEMECHACO)', 'AMEB SALUD (FEMECHACO)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (8, 'AMEBPBA- BANCO PROVINCIA', 'AMEBPBA- BANCO PROVINCIA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (9, 'AMERICAN ASSIST ARGENTINA', 'AMERICAN ASSIST ARGENTINA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (10, 'AMFFA ADHERENTES', 'AMFFA ADHERENTES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (11, 'AMFFA CAFAR', 'AMFFA CAFAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (12, 'AMM-Mut Medicos Munic CABA', 'AMM-Mut Medicos Munic CABA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (13, 'AMPAR -Asoc Mut Pers Philips Arg', 'AMPAR -Asoc Mut Pers Philips Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (14, 'AMPER', 'AMPER', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (15, 'AMSA PLAN OMBU', 'AMSA PLAN OMBU', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (16, 'AMSCA- ASOC MUT ARQUITECTOS', 'AMSCA- ASOC MUT ARQUITECTOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (17, 'ANDAR -Viajantes Vendedores RA', 'ANDAR -Viajantes Vendedores RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (18, 'APDIS -Asoc Pers Direc Ind Siderurgica', 'APDIS -Asoc Pers Direc Ind Siderurgica', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (19, 'APDJIC -Asoc Pers Direc y Jerarq Ind del Cigarrillo', 'APDJIC -Asoc Pers Direc y Jerarq Ind del Cigarrillo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (20, 'APOS LA RIOJA', 'APOS LA RIOJA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (21, 'APRES S.A.', 'APRES S.A.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (22, 'APROSS (EX-IPAM)', 'APROSS (EX-IPAM)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (23, 'APSOT -Asoc Pers Superiorde la Organizacion Techint', 'APSOT -Asoc Pers Superiorde la Organizacion Techint', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (24, 'ASE -Accion Social de Empresarios', 'ASE -Accion Social de Empresarios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (25, 'Asoc de Os Bella Vista', 'Asoc de Os Bella Vista', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (26, 'Asoc de Os Comodoro Rivadavia', 'Asoc de Os Comodoro Rivadavia', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (27, 'Asoc de Os San Juan', 'Asoc de Os San Juan', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (28, 'Asoc de Os Trelew', 'Asoc de Os Trelew', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (29, 'ASOC.ECLES.SAN PEDRO -', 'ASOC.ECLES.SAN PEDRO -', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (30, 'ASSPE -Empres y Pers Direc De Empr Com, Serv, Prod, Ind y Civil', 'ASSPE -Empres y Pers Direc De Empr Com, Serv, Prod, Ind y Civil', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (31, 'Atanor S.A', 'Atanor S.A', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (32, 'AUSTRAL SALUD', 'AUSTRAL SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (33, 'BASA SALUD', 'BASA SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (34, 'BOREAL MEDICINA PREPAGA (SALTA)', 'BOREAL MEDICINA PREPAGA (SALTA)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (35, 'BRISTOL MEDICINE', 'BRISTOL MEDICINE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (36, 'Cabot Arg', 'Cabot Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (37, 'CAFASUR- OS DE CERAMISTAS', 'CAFASUR- OS DE CERAMISTAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (38, 'CAJA DE SERVICIOS SOCIALES (SANTA CRUZ)', 'CAJA DE SERVICIOS SOCIALES (SANTA CRUZ)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (39, 'CAJA NOTARIAL C.S.S.COL.DE ESCRIBANOS', 'CAJA NOTARIAL C.S.S.COL.DE ESCRIBANOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (40, 'CAMPSIC -Pers Sup Ind Del Caucho y Otras Actividades Ind', 'CAMPSIC -Pers Sup Ind Del Caucho y Otras Actividades Ind', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (41, 'CASA', 'CASA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (42, 'CEFRAN', 'CEFRAN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (43, 'CEMIC', 'CEMIC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (44, 'CENTRO MEDICO GALILEO', 'CENTRO MEDICO GALILEO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (45, 'CENTRO MEDICO PUEYRREDON', 'CENTRO MEDICO PUEYRREDON', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (46, 'CLASS INTERNATIONAL', 'CLASS INTERNATIONAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (47, 'CM SALUD CIRC.MEDICO VICENTE LOPEZ', 'CM SALUD CIRC.MEDICO VICENTE LOPEZ', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (48, 'COLMED', 'COLMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (49, 'COMEI', 'COMEI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (50, 'COMI', 'COMI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (51, 'Comisarios Navales', 'Comisarios Navales', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (52, 'Compania Minera Aguilar S.A', 'Compania Minera Aguilar S.A', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (53, 'COMPIR - Soc Pirelli Ltda.', 'COMPIR - Soc Pirelli Ltda.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (54, 'Conduct Camion y Transp Automotor de Cargas', 'Conduct Camion y Transp Automotor de Cargas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (55, 'Conductores de Transp Colectivo de Pasajeros', 'Conductores de Transp Colectivo de Pasajeros', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (56, 'CONSOLIDAR Salud', 'CONSOLIDAR Salud', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (57, 'CONSTRUIR SALUD', 'CONSTRUIR SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (58, 'COVER SALUD', 'COVER SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (59, 'CREDILOGROS', 'CREDILOGROS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (60, 'CS SALUD', 'CS SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (61, 'DAS', 'DAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (62, 'DASMI UNIV.de LUJAN', 'DASMI UNIV.de LUJAN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (63, 'DASUTEN', 'DASUTEN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (64, 'DGBPFA (EX OSFA)', 'DGBPFA (EX OSFA)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (65, 'DIBA', 'DIBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (66, 'Direc Osdo', 'Direc Osdo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (67, 'Dirección Witcel', 'Dirección Witcel', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (68, 'DITEM -Direct, Tecn y Empl John Deere Arg', 'DITEM -Direct, Tecn y Empl John Deere Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (69, 'DOS SAN JUAN', 'DOS SAN JUAN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (70, 'DOSEP', 'DOSEP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (71, 'DOSUBA', 'DOSUBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (72, 'Empl y Pers Jerarq Neumaticos Good Year Srl', 'Empl y Pers Jerarq Neumaticos Good Year Srl', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (73, 'EUROSALUD', 'EUROSALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (74, 'FAAFutbolistas', 'FAAFutbolistas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (75, 'FAMILY SALUD', 'FAMILY SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (76, 'FEBOS', 'FEBOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (77, 'Fed Gremial de la Ind de Carne y deriv', 'Fed Gremial de la Ind de Carne y deriv', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (78, 'FEDECAMARAS- Fed Cam y Centros Comerc Zonales RA', 'FEDECAMARAS- Fed Cam y Centros Comerc Zonales RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (79, 'FEMEBA', 'FEMEBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (80, 'FEMECHACO', 'FEMECHACO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (81, 'FEMEDICA', 'FEMEDICA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (82, 'Ford Agentina S.C.A', 'Ford Agentina S.C.A', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (83, 'FRUTOS -Pers Direc Empresas Frutos del Pais', 'FRUTOS -Pers Direc Empresas Frutos del Pais', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (84, 'GALENO', 'GALENO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (85, 'GENESEN', 'GENESEN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (86, 'GERDANNA SALUD', 'GERDANNA SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (87, 'GRUPO GERENCIAR', 'GRUPO GERENCIAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (88, 'GRUPO RED TOTAL', 'GRUPO RED TOTAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (89, 'Guincheros y Maquinistas de Gruas Moviles', 'Guincheros y Maquinistas de Gruas Moviles', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (90, 'HEALTH MEDICAL', 'HEALTH MEDICAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (91, 'HOPE', 'HOPE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (92, 'HOSP. ALEMAN', 'HOSP. ALEMAN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (93, 'HOSP. BRITANICO PLAN SALUD', 'HOSP. BRITANICO PLAN SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (94, 'HOSP. ITALIANO', 'HOSP. ITALIANO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (95, 'HOSP.FRANCES', 'HOSP.FRANCES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (96, 'IAPOS (SANTA FE)', 'IAPOS (SANTA FE)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (97, 'INSSSEP (CHACO)', 'INSSSEP (CHACO)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (98, 'Inst Nac Serv Soc Jubilados y Pensionados', 'Inst Nac Serv Soc Jubilados y Pensionados', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (99, 'INST.DE SEGUROS DE JUJUY', 'INST.DE SEGUROS DE JUJUY', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (100, 'IOMA', 'IOMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (101, 'IOSCOR (CORRIENTES)', 'IOSCOR (CORRIENTES)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (102, 'IOSE', 'IOSE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (103, 'IOSEP (SANTIAGO DEL ESTERO)', 'IOSEP (SANTIAGO DEL ESTERO)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (104, 'IOSPER (COL.FARM.DE ENTRE RIOS)', 'IOSPER (COL.FARM.DE ENTRE RIOS)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (105, 'IPROSS RIO NEGRO', 'IPROSS RIO NEGRO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (106, 'IPS (SALTA)', 'IPS (SALTA)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (107, 'IPSM (MISIONES)', 'IPSM (MISIONES)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (108, 'IPSST (TUCUMAN)', 'IPSST (TUCUMAN)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (109, 'ISSN (NEUQUEN)', 'ISSN (NEUQUEN)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (110, 'ITALMED', 'ITALMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (111, 'JERARQUICOS SALUD- Pers Jerarq Bancos', 'JERARQUICOS SALUD- Pers Jerarq Bancos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (112, 'JOHNSON -Ceras Johnson', 'JOHNSON -Ceras Johnson', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (113, 'LA RECIPROCA', 'LA RECIPROCA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (114, 'Maquinistas de Teatro y Television', 'Maquinistas de Teatro y Television', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (115, 'MASSALIN PARTICULARES', 'MASSALIN PARTICULARES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (116, 'MEDICENTER', 'MEDICENTER', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (117, 'MEDICINA PRIVADA', 'MEDICINA PRIVADA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (118, 'MEDICUS', 'MEDICUS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (119, 'MEDICUS OSTEL', 'MEDICUS OSTEL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (120, 'MEDIFE 633', 'MEDIFE 633', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (121, 'MEDIFE ASOC.CIVIL', 'MEDIFE ASOC.CIVIL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (122, 'MEDIMAPFRE', 'MEDIMAPFRE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (123, 'MEDIN', 'MEDIN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (124, 'MET CORDOBA', 'MET CORDOBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (125, 'MITA -Mutualidad Ind Textil Arg', 'MITA -Mutualidad Ind Textil Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (126, 'MOA - Mutual Odontológica Arg', 'MOA - Mutual Odontológica Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (127, 'Mut Pers Agua y Energia Electrica Cap Fed', 'Mut Pers Agua y Energia Electrica Cap Fed', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (128, 'Mut Pers Agua y Energia Mendoza', 'Mut Pers Agua y Energia Mendoza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (129, 'MUTUAL FEDERADA', 'MUTUAL FEDERADA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (130, 'MUTUAL SOCIOS CIRC.MEDICO PILAR', 'MUTUAL SOCIOS CIRC.MEDICO PILAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (131, 'Mutualidad Empleados Firestone', 'Mutualidad Empleados Firestone', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (132, 'NO TIENE', 'NO TIENE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (133, 'Obreros Empacadores Fruta Rio Negro y Neuquen', 'Obreros Empacadores Fruta Rio Negro y Neuquen', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (134, 'ObSBA- OS CABA', 'ObSBA- OS CABA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (135, 'OMINT', 'OMINT', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (136, 'OPdeA -Direc Empresas de la Alimentacion', 'OPdeA -Direc Empresas de la Alimentacion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (137, 'OPTAR', 'OPTAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (138, 'OPZC -Ind Quim y Petroquim Zarate Campana', 'OPZC -Ind Quim y Petroquim Zarate Campana', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (139, 'OS DE FUTBOLISTAS', 'OS DE FUTBOLISTAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (140, 'OSde la POLICIA FED.ARG', 'OSde la POLICIA FED.ARG', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (141, 'OS PETROLEROS PLAN 40', 'OS PETROLEROS PLAN 40', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (142, 'OS PETROLEROS PLAN 40 PMO', 'OS PETROLEROS PLAN 40 PMO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (143, 'OS PETROLEROS PLAN 50', 'OS PETROLEROS PLAN 50', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (144, 'OS PETROLEROS PLAN 70', 'OS PETROLEROS PLAN 70', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (145, 'OSA -Actores', 'OSA -Actores', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (146, 'OSA -Aeronavegantes', 'OSA -Aeronavegantes', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (147, 'OSADEF -Asoc Empleados de Farmacia', 'OSADEF -Asoc Empleados de Farmacia', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (148, 'OSADRA -Arbitros Deportivos de la RA', 'OSADRA -Arbitros Deportivos de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (149, 'OSALARA -Agentes de Loterias y Afines de la RA', 'OSALARA -Agentes de Loterias y Afines de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (150, 'OSAM -Actividad Minera', 'OSAM -Actividad Minera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (151, 'OSAMMVC -Asoc Mutual Metalurgica Villa Constitucion', 'OSAMMVC -Asoc Mutual Metalurgica Villa Constitucion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (152, 'OSAMOC -Asoc Mut Obr Catol "Padre Federico Grote"', 'OSAMOC -Asoc Mut Obr Catol "Padre Federico Grote"', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (153, 'OSAPM -Agentes de Propaganda Medica RA', 'OSAPM -Agentes de Propaganda Medica RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (154, 'OSAPMER -Agentes de Propaganda Medica Entre Rios', 'OSAPMER -Agentes de Propaganda Medica Entre Rios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (155, 'OSARPyH -Alfajor, Repost, Pizz y Helad', 'OSARPyH -Alfajor, Repost, Pizz y Helad', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (156, 'OSBA -Bancaria Arg', 'OSBA -Bancaria Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (157, 'OSBARA -Boxeadores Agremiados de la RA', 'OSBARA -Boxeadores Agremiados de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (158, 'OSCAMGLyP -Azulejos, Mosaicos, Granit, Lustr y Porcel', 'OSCAMGLyP -Azulejos, Mosaicos, Granit, Lustr y Porcel', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (159, 'OSCAPBAQFLU -Cap Baq Fluviales Marina Mercante', 'OSCAPBAQFLU -Cap Baq Fluviales Marina Mercante', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (160, 'OSCE -Ceramistas', 'OSCE -Ceramistas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (161, 'OSCEP -Capataces Estibadores Portuarios', 'OSCEP -Capataces Estibadores Portuarios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (162, 'OSCHOCA -Choferes de Camiones', 'OSCHOCA -Choferes de Camiones', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (163, 'OSCICA -Camara Ind Curtidora Arg', 'OSCICA -Camara Ind Curtidora Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (164, 'OSCOEMA -Confed Obreros y Empleados Munic Arg', 'OSCOEMA -Confed Obreros y Empleados Munic Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (165, 'OSCOMM -Cap Ultramar y Oficiales Marina Mer', 'OSCOMM -Cap Ultramar y Oficiales Marina Mer', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (166, 'OSCONARA -Conductores Navales', 'OSCONARA -Conductores Navales', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (167, 'OSCRAIA -Conductores de Remises', 'OSCRAIA -Conductores de Remises', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (168, 'OSDE -Ejecutivos y Pers Direc de Empresas', 'OSDE -Ejecutivos y Pers Direc de Empresas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (169, 'OSDEL -Locutores', 'OSDEL -Locutores', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (170, 'OSDEM -Musicos', 'OSDEM -Musicos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (171, 'OSDEPyM -Empresarios, Prof y Monotributistas', 'OSDEPyM -Empresarios, Prof y Monotributistas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (172, 'OSDIC -Pers Directivo Ind de la Construccion', 'OSDIC -Pers Directivo Ind de la Construccion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (173, 'OSDIPP -Pers Direc Ind Privada del Petroleo', 'OSDIPP -Pers Direc Ind Privada del Petroleo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (174, 'OSDOP -Docentes Particulares', 'OSDOP -Docentes Particulares', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (175, 'OSEADI -Empleados de Agencias de Informes', 'OSEADI -Empleados de Agencias de Informes', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (176, 'OSEAM -Encargados Apuntadores Maritimos', 'OSEAM -Encargados Apuntadores Maritimos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (177, 'OSECAC -Empleados de Comercio y Actividades Civiles', 'OSECAC -Empleados de Comercio y Actividades Civiles', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (178, 'OSEDA -Empleados de Despachantes de Aduana', 'OSEDA -Empleados de Despachantes de Aduana', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (179, 'OSEDEIV -Pers Direc Ind Vitivinicola', 'OSEDEIV -Pers Direc Ind Vitivinicola', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (180, 'OSEIV -Empleados Ind Del Vidrio', 'OSEIV -Empleados Ind Del Vidrio', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (181, 'OSEMM -Empleados Marina Mercante', 'OSEMM -Empleados Marina Mercante', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (182, 'OSEN -Electricistas Navales', 'OSEN -Electricistas Navales', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (183, 'OSEP (CATAMARCA)', 'OSEP (CATAMARCA)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (184, 'OSEPC -Empleados de Prensa de Cordoba', 'OSEPC -Empleados de Prensa de Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (185, 'OSETRA -Empleados del Tabaco de la RA', 'OSETRA -Empleados del Tabaco de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (186, 'OSETyA -Empleados Textiles y Afines', 'OSETyA -Empleados Textiles y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (187, 'OSFATLyF -Fed Arg de Trab de Luz y Fuerza', 'OSFATLyF -Fed Arg de Trab de Luz y Fuerza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (188, 'OSFATUN -Fed Arg del Trab Univers Nac', 'OSFATUN -Fed Arg del Trab Univers Nac', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (189, 'OSFE -Ferroviaria', 'OSFE -Ferroviaria', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (190, 'OSFFENTOS -Fed Nac de Trab de Obras Sanitarias', 'OSFFENTOS -Fed Nac de Trab de Obras Sanitarias', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (191, 'OSFOT -Fotografos', 'OSFOT -Fotografos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (192, 'OSFyHC -Manip, Empaque y Exped Fruta y Hortalizas Cuyo', 'OSFyHC -Manip, Empaque y Exped Fruta y Hortalizas Cuyo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (193, 'OSIAD -Pers Ind Aceitera, desmotadora y Afines', 'OSIAD -Pers Ind Aceitera, desmotadora y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (194, 'OSIM -Pers Direcde la Ind Metalurgica', 'OSIM -Pers Direcde la Ind Metalurgica', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (195, 'OSIPA -Ind de Pastas Alimenticias', 'OSIPA -Ind de Pastas Alimenticias', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (196, 'OSITAC -Ind del Transporte Automotor de Cordoba', 'OSITAC -Ind del Transporte Automotor de Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (197, 'OSJERA -Pers Jerarqde la RA (Agua y Energia)', 'OSJERA -Pers Jerarqde la RA (Agua y Energia)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (198, 'OSJOMN -Jefes y Oficiales Maquinistas Navales', 'OSJOMN -Jefes y Oficiales Maquinistas Navales', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (199, 'OSJONR -Jefes y Oficiales Navales de Radiocomunic', 'OSJONR -Jefes y Oficiales Navales de Radiocomunic', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (200, 'OSJPVyF -Jardineros, Parquistas, Viveristas y Floricultores', 'OSJPVyF -Jardineros, Parquistas, Viveristas y Floricultores', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (201, 'OSLERA -Legisladores de la RA', 'OSLERA -Legisladores de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (202, 'OSLPASTEUR -Pers Direc de la Sanidad Luis Pasteur', 'OSLPASTEUR -Pers Direc de la Sanidad Luis Pasteur', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (203, 'OSLyF PATAGONIA -Luz y Fuerza Patagonia', 'OSLyF PATAGONIA -Luz y Fuerza Patagonia', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (204, 'OSLyF -Pers Luz y Fuerza Cordoba', 'OSLyF -Pers Luz y Fuerza Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (205, 'OSMA -Modelos Argentinos', 'OSMA -Modelos Argentinos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (206, 'OSMAD -Pers Direc Ind Maderera', 'OSMAD -Pers Direc Ind Maderera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (207, 'OSMATA -Sind de Mecanicos y Af del Transp Automotor', 'OSMATA -Sind de Mecanicos y Af del Transp Automotor', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (208, 'OSME -Pers Minist Economia y Obras y Serv Publ', 'OSME -Pers Minist Economia y Obras y Serv Publ', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (209, 'OSMEBA', 'OSMEBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (210, 'OSMECON SALUD E.ECHEVERRIA', 'OSMECON SALUD E.ECHEVERRIA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (211, 'OSMECON SALUD L.Z.', 'OSMECON SALUD L.Z.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (212, 'OSMECON SALUD MATANZA', 'OSMECON SALUD MATANZA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (213, 'OSMECON SALUD S.MARTIN/3 DE FEB.', 'OSMECON SALUD S.MARTIN/3 DE FEB.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (214, 'OSMECON SALUD SAN ISIDRO', 'OSMECON SALUD SAN ISIDRO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (215, 'OSMEDICA -Medicos de la Ciudad de Bs As', 'OSMEDICA -Medicos de la Ciudad de Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (216, 'OSMISS -Ministros, Secretarios y Subsecretarios', 'OSMISS -Ministros, Secretarios y Subsecretarios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (217, 'OSMITA (GERENFAR)', 'OSMITA (GERENFAR)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (218, 'OSMMEDT -Mandos Medios Telecomunic RA y Mercosur', 'OSMMEDT -Mandos Medios Telecomunic RA y Mercosur', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (219, 'OSOC -Operadores Cinematograficos', 'OSOC -Operadores Cinematograficos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (220, 'OSOETSyLARA -Tintoreros Sombrereros y Lavaderos RA', 'OSOETSyLARA -Tintoreros Sombrereros y Lavaderos RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (221, 'OSOFPP DE ROSARIO -Oficiales Peluq y Peinad Rosario', 'OSOFPP DE ROSARIO -Oficiales Peluq y Peinad Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (222, 'OSOSS -Obras y Servicios Sanitarios', 'OSOSS -Obras y Servicios Sanitarios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (223, 'OSPA -Azucar Ingenio La Esperanza', 'OSPA -Azucar Ingenio La Esperanza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (224, 'OSPA -Azucar Ingenio San Martin', 'OSPA -Azucar Ingenio San Martin', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (225, 'OSPA -Pers Aeronautico', 'OSPA -Pers Aeronautico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (226, 'OSPA -Portuarios Argentinos', 'OSPA -Portuarios Argentinos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (227, 'OSPA -Portuarios Argentinos Mar Del Plata', 'OSPA -Portuarios Argentinos Mar Del Plata', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (228, 'OSPACA -Actividad Cervecera y Afines', 'OSPACA -Actividad Cervecera y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (229, 'OSPACA -Automovil Club Argentino', 'OSPACA -Automovil Club Argentino', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (230, 'OSPACARP', 'OSPACARP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (231, 'OSPACP -Pers Auxiliar Casas Particulares', 'OSPACP -Pers Auxiliar Casas Particulares', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (232, 'OSPADEP -Pers Aeronavegacion de Entes Privados', 'OSPADEP -Pers Aeronavegacion de Entes Privados', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (233, 'OSPAF -Pers Actividad Fruticola', 'OSPAF -Pers Actividad Fruticola', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (234, 'OSPAGA -Pers Aguas Gaseosas y Afines', 'OSPAGA -Pers Aguas Gaseosas y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (235, 'OSPAIL -Pers Azucar Ingenio Ledesma', 'OSPAIL -Pers Azucar Ingenio Ledesma', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (236, 'OSPAÑA -Inmigrantes Español y descend Resid en RA', 'OSPAÑA -Inmigrantes Español y descend Resid en RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (237, 'OSPAP -Pers Actividad Perfumista', 'OSPAP -Pers Actividad Perfumista', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (238, 'OSPAT -Pers Actividad Turf', 'OSPAT -Pers Actividad Turf', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (239, 'OSPATCA -Pers Administr y Tecn Construccion', 'OSPATCA -Pers Administr y Tecn Construccion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (240, 'OSPAV -Pers Actividad Vitivinicola', 'OSPAV -Pers Actividad Vitivinicola', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (241, 'OSPA-VIAL -Pers Actividad Vial', 'OSPA-VIAL -Pers Actividad Vial', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (242, 'OSPCN -Union Pers Civil de la Nacion', 'OSPCN -Union Pers Civil de la Nacion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (243, 'OSPCRA -Pers Cementerios RA', 'OSPCRA -Pers Cementerios RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (244, 'OSPCSPMYA -Pers Ceram, Sanit, Porcelana de Mesa', 'OSPCSPMYA -Pers Ceram, Sanit, Porcelana de Mesa', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (245, 'OSPCyD -Pers Carga y Descarga', 'OSPCyD -Pers Carga y Descarga', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (246, 'OSPDESBA -Pers Direc Empresa Subterraneos Bs As', 'OSPDESBA -Pers Direc Empresa Subterraneos Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (247, 'OSPE -Pers Escribanos', 'OSPE -Pers Escribanos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (248, 'OSPE -Petroleros', 'OSPE -Petroleros', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (249, 'OSPEA -Pers Superior y Prof Empresas Aerocomerciales', 'OSPEA -Pers Superior y Prof Empresas Aerocomerciales', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (250, 'OSPEC -Pers Correos y Telegrafos y Comunicaciones', 'OSPEC -Pers Correos y Telegrafos y Comunicaciones', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (251, 'OSPECA -Pers Caucho', 'OSPECA -Pers Caucho', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (252, 'OSPECON -Pers Construccion', 'OSPECON -Pers Construccion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (253, 'OSPECOR -Petroleros Cordoba', 'OSPECOR -Petroleros Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (254, 'OSPEDICI -Pers Distribuidoras Cinematograficas', 'OSPEDICI -Pers Distribuidoras Cinematograficas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (255, 'OSPEDyC -Pers Entidades Deportivas y Civiles', 'OSPEDyC -Pers Entidades Deportivas y Civiles', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (256, 'OSPEF y EPCA -Pers Fiat y Peugeot Citroen Arg', 'OSPEF y EPCA -Pers Fiat y Peugeot Citroen Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (257, 'OSPEGAP -Petroleo y Gas Privado', 'OSPEGAP -Petroleo y Gas Privado', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (258, 'OSPEJ -Pers Jaboneros', 'OSPEJ -Pers Jaboneros', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (259, 'OSPEMOM -Pers Micros y Omnibus Mendoza', 'OSPEMOM -Pers Micros y Omnibus Mendoza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (260, 'OSPENA -Pers Naval', 'OSPENA -Pers Naval', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (261, 'OSPEP -Pers Espectaculo Publico', 'OSPEP -Pers Espectaculo Publico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (262, 'OSPEP -Pers Enseñanza Privada', 'OSPEP -Pers Enseñanza Privada', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (263, 'OSPEP -Pers Panaderias', 'OSPEP -Pers Panaderias', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (264, 'OSPEPBA -Pers Escribanias Provincia De Bs As', 'OSPEPBA -Pers Escribanias Provincia De Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (265, 'OSPERCIN -Pers Cinematografico Mar Del Plata', 'OSPERCIN -Pers Cinematografico Mar Del Plata', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (266, 'OSPERSAAMS -Pers Asociado a Mutual Sancor', 'OSPERSAAMS -Pers Asociado a Mutual Sancor', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (267, 'OSPERyH -Pers Edific Renta y Htal CABA y GBA', 'OSPERyH -Pers Edific Renta y Htal CABA y GBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (268, 'OSPERyHRA -Pers Edific Renta y Htal RA', 'OSPERyHRA -Pers Edific Renta y Htal RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (269, 'OSPES -Pers Est Serv, Garages, Estac, Lavad y Gomerias', 'OSPES -Pers Est Serv, Garages, Estac, Lavad y Gomerias', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (270, 'OSPESA -Pers Soc Autores y Afines', 'OSPESA -Pers Soc Autores y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (271, 'OSPESCA -Capitanes, Pilotos y Patrones Pesca', 'OSPESCA -Capitanes, Pilotos y Patrones Pesca', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (272, 'OSPESCHA -Pers Est Serv,Garages, Playas y Lav- Chaco', 'OSPESCHA -Pers Est Serv,Garages, Playas y Lav- Chaco', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (273, 'OSPESGA -Pers Est, Garages, Playas y Lav Autom- Santa Fe', 'OSPESGA -Pers Est, Garages, Playas y Lav Autom- Santa Fe', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (274, 'OSPESGyPE -Pers Est Serv, Garages, Playas Estac y Lavad', 'OSPESGyPE -Pers Est Serv, Garages, Playas Estac y Lavad', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (275, 'OSPETAX -Peones Taxis Capital Federal', 'OSPETAX -Peones Taxis Capital Federal', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (276, 'OSPETELCO -Pers Telecomunicaciones Sind Bs As', 'OSPETELCO -Pers Telecomunicaciones Sind Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (277, 'OSPEVIC -Pers Vigil y Seg Com, Ind e Invest Priv Cordoba', 'OSPEVIC -Pers Vigil y Seg Com, Ind e Invest Priv Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (278, 'OSPF -Pers Farmacia', 'OSPF -Pers Farmacia', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (279, 'OSPG -Pers Grafico', 'OSPG -Pers Grafico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (280, 'OSPHGBAySI -Pers Hipodromos De Bs As y San Isidro', 'OSPHGBAySI -Pers Hipodromos De Bs As y San Isidro', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (281, 'OSPIA -Pers Ind Azucarera', 'OSPIA -Pers Ind Azucarera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (282, 'OSPIA -Pers Ind Alimentacion', 'OSPIA -Pers Ind Alimentacion', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (283, 'OSPIB -Pers Ind Botonera', 'OSPIB -Pers Ind Botonera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (284, 'OSPIC -Pers Ind Cinematografica', 'OSPIC -Pers Ind Cinematografica', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (285, 'OSPIC -Pers Ind Del Caucho', 'OSPIC -Pers Ind Del Caucho', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (286, 'OSPIC SANTA FE -Pers Ind del Caucho Santa Fe', 'OSPIC SANTA FE -Pers Ind del Caucho Santa Fe', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (287, 'OSPICA -Pers Ind del Cuero y Afines', 'OSPICA -Pers Ind del Cuero y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (288, 'OSPICAL -Pers Ind del Calzado', 'OSPICAL -Pers Ind del Calzado', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (289, 'OSPICHA -Pers Ind del Chacinado y Afines', 'OSPICHA -Pers Ind del Chacinado y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (290, 'OSPIDA -Pers Imprenta, Diarios y Afines', 'OSPIDA -Pers Imprenta, Diarios y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (291, 'OSPIF -Pers Ind Fibrocemento', 'OSPIF -Pers Ind Fibrocemento', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (292, 'OSPIF -Pers Ind del Fosforo, Encendido y Afines', 'OSPIF -Pers Ind del Fosforo, Encendido y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (293, 'OSPIF -Pers Ind Fideera', 'OSPIF -Pers Ind Fideera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (294, 'OSPIFSE -Pers Ind Forestal Santiago Del Estero', 'OSPIFSE -Pers Ind Forestal Santiago Del Estero', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (295, 'OSPIHMP -Pers Ind Hielo y Mercados Particulares', 'OSPIHMP -Pers Ind Hielo y Mercados Particulares', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (296, 'OSPIL -Pers Ind Lechera', 'OSPIL -Pers Ind Lechera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (297, 'OSPILM -Pers Ind Ladrillera a Maquina', 'OSPILM -Pers Ind Ladrillera a Maquina', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (298, 'OSPIM -Pers Ind Maderera', 'OSPIM -Pers Ind Maderera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (299, 'OSPIM -Pers Ind Molinera', 'OSPIM -Pers Ind Molinera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (300, 'OSPIN -Pers Ind del Neumatico', 'OSPIN -Pers Ind del Neumatico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (301, 'OSPIN -Pers Ind Naval', 'OSPIN -Pers Ind Naval', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (302, 'OSPIP -Pers Ind del Plastico', 'OSPIP -Pers Ind del Plastico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (303, 'OSPIP -Pers Ind Petroquimica', 'OSPIP -Pers Ind Petroquimica', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (304, 'OSPIQyP -Pers Ind Quimicas y Petroquimicas', 'OSPIQyP -Pers Ind Quimicas y Petroquimicas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (305, 'OSPIS -Pers Instalaciones Sanitarias', 'OSPIS -Pers Instalaciones Sanitarias', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (306, 'OSPIT -Pers Ind del Tabaco', 'OSPIT -Pers Ind del Tabaco', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (307, 'OSPIT -Pers Ind del Tractor', 'OSPIT -Pers Ind del Tractor', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (308, 'OSPIT -Pers Ind Textil', 'OSPIT -Pers Ind Textil', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (309, 'OSPIV -Pers Ind del Vestido', 'OSPIV -Pers Ind del Vestido', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (310, 'OSPIV -Pers Ind del Vidrio', 'OSPIV -Pers Ind del Vidrio', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (311, 'OSPL -Pers Ladrillero', 'OSPL -Pers Ladrillero', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (312, 'OSPLA -Pilotos Lineas Aereas Comerc y Regul', 'OSPLA -Pilotos Lineas Aereas Comerc y Regul', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (313, 'OSPLAD -Actividad Docente', 'OSPLAD -Actividad Docente', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (314, 'OSPM -Pers Maestranza', 'OSPM -Pers Maestranza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (315, 'OSPM -Pers Maritimo', 'OSPM -Pers Maritimo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (316, 'OSPM -Pers Mosaista', 'OSPM -Pers Mosaista', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (317, 'OSPOCE -Pers Organismo Control Externo', 'OSPOCE -Pers Organismo Control Externo', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (318, 'OSPP -Pers Publicidad', 'OSPP -Pers Publicidad', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (319, 'OSPPCHA -Pers Prensa Chaco', 'OSPPCHA -Pers Prensa Chaco', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (320, 'OSPPCyQ -Pers Papel, Carton y Quimicos', 'OSPPCyQ -Pers Papel, Carton y Quimicos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (321, 'OSPPEA -Pers Peluquerias, Esteticas y Afines', 'OSPPEA -Pers Peluquerias, Esteticas y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (322, 'OSPPRA -Pers Prensa de la RA', 'OSPPRA -Pers Prensa de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (323, 'OSPREME -Pers Direc de la Ind Automotriz Arg', 'OSPREME -Pers Direc de la Ind Automotriz Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (324, 'OSPREN -Pers Prensa Mar Del Plata', 'OSPREN -Pers Prensa Mar Del Plata', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (325, 'OSPRENTUC -Pers Prensa Tucuman', 'OSPRENTUC -Pers Prensa Tucuman', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (326, 'OSPRERA -Pers Rural y Estibadores RA', 'OSPRERA -Pers Rural y Estibadores RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (327, 'OSPRO -Pers Prensa Rosario', 'OSPRO -Pers Prensa Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (328, 'OSPROTURA -Prof Turf de la RA', 'OSPROTURA -Prof Turf de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (329, 'OSPS MERCEDES -Pers Superior Mercedes Benz Arg', 'OSPS MERCEDES -Pers Superior Mercedes Benz Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (330, 'OSPSA -Pers Sanidad Arg', 'OSPSA -Pers Sanidad Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (331, 'OSPSESBA -Pers Supervision Empr Subterraneos Bs As', 'OSPSESBA -Pers Supervision Empr Subterraneos Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (332, 'OSPSIP -Pers Segur Com, Ind e Investig Priv', 'OSPSIP -Pers Segur Com, Ind e Investig Priv', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (333, 'OSPTA -Pers Tecnico Aeronautico', 'OSPTA -Pers Tecnico Aeronautico', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (334, 'OSPTV -Pers Television', 'OSPTV -Pers Television', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (335, 'OSPUAyE -Prof Univers Del Agua y La Energia Electrica', 'OSPUAyE -Prof Univers Del Agua y La Energia Electrica', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (336, 'OSRGA -Recibidores Granos y Anexos', 'OSRGA -Recibidores Granos y Anexos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (337, 'OSRJA -Relojeros y Joyeros', 'OSRJA -Relojeros y Joyeros', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (338, 'OSRM -Refinerias De Maiz S.A.I.C.F.', 'OSRM -Refinerias De Maiz S.A.I.C.F.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (339, 'OSSACRA -Asoc Civil Prosind Amas de Casa RA', 'OSSACRA -Asoc Civil Prosind Amas de Casa RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (340, 'OSSEG -Seg, Reaseg, Capital y Ahorro y Prest Viv', 'OSSEG -Seg, Reaseg, Capital y Ahorro y Prest Viv', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (341, 'OSSIMRA -Supervis de la Ind Metalmecanicade la RA', 'OSSIMRA -Supervis de la Ind Metalmecanicade la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (342, 'OSSPyFER -Panad, Pastel y Factur Entre Rios', 'OSSPyFER -Panad, Pastel y Factur Entre Rios', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (343, 'OSTAD -Talleristas A Domicilio', 'OSTAD -Talleristas A Domicilio', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (344, 'OSTAMMA -Trab Asoc a Mutual Mercantil Arg', 'OSTAMMA -Trab Asoc a Mutual Mercantil Arg', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (345, 'OSTC -Conductores de Taxis Cordoba', 'OSTC -Conductores de Taxis Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (346, 'OSTCARA -Trab Carne y Afines RA', 'OSTCARA -Trab Carne y Afines RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (347, 'OSTECF -Tecnicos de Futbol', 'OSTECF -Tecnicos de Futbol', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (348, 'OSTEE -Trabde la s Empresas de Electricidad', 'OSTEE -Trabde la s Empresas de Electricidad', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (349, 'OSTEL -Pers Telecomunicaciones de la RA', 'OSTEL -Pers Telecomunicaciones de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (350, 'OSTEP -Educacion Privada', 'OSTEP -Educacion Privada', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (351, 'OSTES -Estaciones de Servicio', 'OSTES -Estaciones de Servicio', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (352, 'OSTIG -Ind Del Gas', 'OSTIG -Ind Del Gas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (353, 'OSTP -Perkins Arg S.A.I.C', 'OSTP -Perkins Arg S.A.I.C', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (354, 'OSTPBA -Prensa Bs As', 'OSTPBA -Prensa Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (355, 'OSTPCHPyARA -Pastel, Confit, Pizz, Helad y Alfajor', 'OSTPCHPyARA -Pastel, Confit, Pizz, Helad y Alfajor', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (356, 'OSTRAC -Comunicaciones', 'OSTRAC -Comunicaciones', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (357, 'OSTRAC-AATRAC -', 'OSTRAC-AATRAC -', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (358, 'OSTV -', 'OSTV -', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (359, 'OSTVENDRA -Trab Vendedores Diarios Revistas y Afines', 'OSTVENDRA -Trab Vendedores Diarios Revistas y Afines', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (360, 'OSTVLA -Tecnicos de Vuelo de Lineas Aereas', 'OSTVLA -Tecnicos de Vuelo de Lineas Aereas', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (361, 'OSUCI -Cortadores Indumentaria', 'OSUCI -Cortadores Indumentaria', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (362, 'OSUOMRA -Union Obrera Metalurgica de la RA', 'OSUOMRA -Union Obrera Metalurgica de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (363, 'OSUTHGRA -Union Trab Turismo Hotel y Gastronom RA', 'OSUTHGRA -Union Trab Turismo Hotel y Gastronom RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (364, 'OSVARA -Vendedores Ambulantes RA', 'OSVARA -Vendedores Ambulantes RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (365, 'OSYPF -YPF', 'OSYPF -YPF', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (366, 'OTRAS', 'OTRAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (367, 'PAMI', 'PAMI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (368, 'Papel Misionero S.A.I.F. y C.', 'Papel Misionero S.A.I.F. y C.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (369, 'Patrones De Cabotaje De Rios y Puertos', 'Patrones De Cabotaje De Rios y Puertos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (370, 'Pers Barracasde la nas, Cueros y Anexos', 'Pers Barracasde la nas, Cueros y Anexos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (371, 'Pers Consignat Merc Hacienda Liniers', 'Pers Consignat Merc Hacienda Liniers', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (372, 'Pers Direc Alfredo Fortabat', 'Pers Direc Alfredo Fortabat', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (373, 'Pers Empr Limpieza, Servicios y Maestranza Mendoza', 'Pers Empr Limpieza, Servicios y Maestranza Mendoza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (374, 'Pers Ind Grafica Cordoba', 'Pers Ind Grafica Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (375, 'Pers Jerarq Transp Automotor Pasaj Cordoba', 'Pers Jerarq Transp Automotor Pasaj Cordoba', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (376, 'Pers Jockey Club De Rosario', 'Pers Jockey Club De Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (377, 'Pers Mensualizado Jockey Club Bs As e Hipodromos', 'Pers Mensualizado Jockey Club Bs As e Hipodromos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (378, 'Pers Municipal Avellaneda', 'Pers Municipal Avellaneda', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (379, 'Pers Municipal La Matanza', 'Pers Municipal La Matanza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (380, 'Pers Municipal Tres De Febrero', 'Pers Municipal Tres De Febrero', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (381, 'Pers PBBpolisur SA Bahia Blanca', 'Pers PBBpolisur SA Bahia Blanca', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (382, 'Pers Prensa Bahia Blanca', 'Pers Prensa Bahia Blanca', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (383, 'Pers Prensa Mendoza', 'Pers Prensa Mendoza', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (384, 'Pers Recoleccion y Barrido Rosario', 'Pers Recoleccion y Barrido Rosario', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (385, 'Pers Refinerias de Maiz', 'Pers Refinerias de Maiz', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (386, 'Pers Shell-Capsa', 'Pers Shell-Capsa', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (387, 'Pers Univers Nac de la Patagonia San Juan Bosco', 'Pers Univers Nac de la Patagonia San Juan Bosco', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (388, 'Pers Univers Nac del Centro de Pcia de Bs As', 'Pers Univers Nac del Centro de Pcia de Bs As', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (389, 'PLAMED', 'PLAMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (390, 'PLANAMED', 'PLANAMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (391, 'PODER JUDICIAL de la NACION-', 'PODER JUDICIAL de la NACION-', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (392, 'POLICLINICO LOMAS', 'POLICLINICO LOMAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (393, 'Portuarios de Puerto San Martin y Bella Vista', 'Portuarios de Puerto San Martin y Bella Vista', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (394, 'PREVENSALUD (SALUD JUJUY)', 'PREVENSALUD (SALUD JUJUY)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (395, 'PROFE', 'PROFE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (396, 'SADAIC', 'SADAIC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (397, 'SAMA', 'SAMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (398, 'SAMI C.M.MATANZA', 'SAMI C.M.MATANZA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (399, 'SAMI SALUD', 'SAMI SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (400, 'SANATORIO GUEMES', 'SANATORIO GUEMES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (401, 'SANCOR SALUD CAP./GBA', 'SANCOR SALUD CAP./GBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (402, 'SANTIAGO SALUD', 'SANTIAGO SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (403, 'SCIS', 'SCIS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (404, 'SEMESA (OCYFA)', 'SEMESA (OCYFA)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (405, 'SEMPRE (LA PAMPA )', 'SEMPRE (LA PAMPA )', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (406, 'Serenos de Buques', 'Serenos de Buques', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (407, 'SEROS', 'SEROS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (408, 'SERVESALUD- Pers Direc Ind Cervecera y Maltera', 'SERVESALUD- Pers Direc Ind Cervecera y Maltera', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (409, 'Sind Unido Trab Ind De Aguas Gaseosas Santa Fe', 'Sind Unido Trab Ind De Aguas Gaseosas Santa Fe', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (410, 'SINDICATO TRABAJ.MUNICIPALES', 'SINDICATO TRABAJ.MUNICIPALES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (411, 'SISTEMA MEDICO CONSEJO', 'SISTEMA MEDICO CONSEJO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (412, 'SMAI', 'SMAI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (413, 'SOEME', 'SOEME', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (414, 'SOMU- PERS MARITIMO', 'SOMU- PERS MARITIMO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (415, 'SOSBA', 'SOSBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (416, 'STAFF MEDICO', 'STAFF MEDICO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (417, 'SUME', 'SUME', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (418, 'Superco', 'Superco', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (419, 'SUTEBA-IOMA', 'SUTEBA-IOMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (420, 'SUTEBA-OSPLAD', 'SUTEBA-OSPLAD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (421, 'SWISS MEDICAL GROUP', 'SWISS MEDICAL GROUP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (422, 'TARJETA FARMACEUTICA BONAERENSE', 'TARJETA FARMACEUTICA BONAERENSE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (423, 'Trab Viales y Afines de la RA', 'Trab Viales y Afines de la RA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (424, 'TV SALUD (EX OSPTV)', 'TV SALUD (EX OSPTV)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (425, 'UAI SALUD', 'UAI SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (426, 'UDOCBA', 'UDOCBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (427, 'UNION PERSONAL ACCORD AREA METR.', 'UNION PERSONAL ACCORD AREA METR.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (428, 'UNION PERSONAL ACCORD PROV.BS.AS.', 'UNION PERSONAL ACCORD PROV.BS.AS.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (429, 'UNION PERSONAL CLASSIC/FAM AREA MET.', 'UNION PERSONAL CLASSIC/FAM AREA MET.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (430, 'UNION PERSONAL CLASSIC/FAM.PROV.BS.AS.', 'UNION PERSONAL CLASSIC/FAM.PROV.BS.AS.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (431, 'UNIVERSIDADde la PLATA', 'UNIVERSIDADde la PLATA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (432, 'UNO SALUD', 'UNO SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (433, 'UPCN SECC.CAP.FED.', 'UPCN SECC.CAP.FED.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (434, 'UPFPARA -Pers Fabricas de Pintura', 'UPFPARA -Pers Fabricas de Pintura', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (435, 'Vareadores', 'Vareadores', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (436, 'Volkswagen Arg S.A.', 'Volkswagen Arg S.A.', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (437, 'WHOPE -Pers Direc De Perfumeria E.W. Hope', 'WHOPE -Pers Direc De Perfumeria E.W. Hope', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (438, 'Yacimientos Carboniferos', 'Yacimientos Carboniferos', 'Active');
SELECT setval('hc_common_socialservice_id_seq', 438);
