# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0002_auto_20160603_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='bornPlace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fatherSurname',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='persona',
            name='firstName',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='persona',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otherNames',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='socialServiceNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
