# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


def loadCivilStatusType(apps, schema_editor):
    CivilStatusType = apps.get_model("hc_common", "CivilStatusType")

    CivilStatusType(
        name="Soltero",
        description="Soltero",
        status="Active"
        ).save()

    CivilStatusType(
        name="Casado",
        description="Casado",
        status="Active"
        ).save()

    CivilStatusType(
        name="Divorciado",
        description="Divorciado",
        status="Active"
        ).save()

    CivilStatusType(
        name="Viudo",
        description="Viudo",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0002_auto_20160603_0913'),
    ]

    operations = [
        migrations.RunPython(loadCivilStatusType),
    ]
