# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:41
from __future__ import unicode_literals

from django.db import migrations


def loadDocumentType(apps, schema_editor):
    DocumentType = apps.get_model("hc_common", "DocumentType")

    DocumentType(
        name="DNI",
        status="Active"
        ).save()

    DocumentType(
        name="LI",
        status="Active"
        ).save()

    DocumentType(
        name="LC",
        status="Active"
        ).save()

    DocumentType(
        name="PASS",
        description="Pasaporte",
        status="Active"
        ).save()

    DocumentType(
        name="NIF",
        description="No informa",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0003_auto_20160616_1111'),
    ]

    operations = [
        migrations.RunPython(loadDocumentType),
    ]
