# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-29 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0003_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialservice',
            options={'ordering': ['-order', 'name']},
        ),
        migrations.AddField(
            model_name='socialservice',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
