# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0004_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilstatustype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='educationtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['fatherSurname']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sextype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='socialservice',
            options={'ordering': ['name']},
        ),
    ]
