# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:41
from __future__ import unicode_literals

from django.db import migrations


def loadEducationType(apps, schema_editor):
    EducationType = apps.get_model("hc_common", "EducationType")

    EducationType(
        name="Inicial",
        description="Inicial",
        status="Active"
        ).save()

    EducationType(
        name="Primaria",
        description="Primaria",
        status="Active"
        ).save()

    EducationType(
        name="Secundaria",
        description="Secundaria",
        status="Active"
        ).save()

    EducationType(
        name="Terceria",
        description="Terceria",
        status="Active"
        ).save()

    EducationType(
        name="Universiatario",
        description="Universiatario",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0004_auto_20160616_1141'),
    ]

    operations = [
        migrations.RunPython(loadEducationType),
    ]
