# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:41
from __future__ import unicode_literals

from django.db import migrations


def loadProvince(apps, schema_editor):
    Province = apps.get_model("hc_common", "Province")

    Province(
        name="Buenos Aires",
        status="Active"
        ).save()

    Province(
        name="CABA",
        description="Ciudad Autónoma de Buenos Aires",
        status="Active"
        ).save()

    Province(
        name="Cordoba",
        status="Active"
        ).save()

    Province(
        name="Santa Fe",
        status="Active"
        ).save()

    Province(
        name="Entre Rios",
        status="Active"
        ).save()

    Province(
        name="Corrientes",
        status="Active"
        ).save()

    Province(
        name="Misiones",
        status="Active"
        ).save()

    Province(
        name="Chaco",
        status="Active"
        ).save()

    Province(
        name="Salta",
        status="Active"
        ).save()

    Province(
        name="Jujuy",
        status="Active"
        ).save()

    Province(
        name="Tucuman",
        status="Active"
        ).save()

    Province(
        name="Santiago del Estero",
        status="Active"
        ).save()

    Province(
        name="Mendoza",
        status="Active"
        ).save()

    Province(
        name="Catamarca",
        status="Active"
        ).save()

    Province(
        name="La Pampa",
        status="Active"
        ).save()

    Province(
        name="Rio Negro",
        status="Active"
        ).save()

    Province(
        name="Chubut",
        status="Active"
        ).save()

    Province(
        name="Tierra del Fuego",
        status="Active"
        ).save()

    Province(
        name="La Rioja",
        status="Active"
        ).save()

    Province(
        name="Santa Cruz",
        status="Active"
        ).save()

    Province(
        name="Neuquén",
        status="Active"
        ).save()

    Province(
        name="San Luis",
        status="Active"
        ).save()

    Province(
        name="San Juan",
        status="Active"
        ).save()

    Province(
        name="Formosa",
        status="Active"
        ).save()

    Province(
        name="No informa",
        description="No informa",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0005_auto_20160616_1141'),
    ]

    operations = [
        migrations.RunPython(loadProvince),
    ]
