# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0005_auto_20160626_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='terms',
        ),
    ]
