# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 14:41
from __future__ import unicode_literals

from django.db import migrations


def loadSexType(apps, schema_editor):
    SexType = apps.get_model("hc_common", "SexType")

    SexType(
        name="Masculino",
        description="Masculino",
        status="Active"
        ).save()

    SexType(
        name="Femenino",
        description="Femenino",
        status="Active"
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0006_auto_20160616_1141'),
    ]

    operations = [
        migrations.RunPython(loadSexType),
    ]
