# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:14
from __future__ import unicode_literals

from django.db import migrations


def loadLocation(apps, schema_editor):
    District = apps.get_model("hc_common", "District")
    Location = apps.get_model("hc_common", "Location")

    Location(
        name="No informa",
        description="No informa",
        status="Active",
        district=District.objects.get(name="No informa")
        ).save()

    Location(
        name="CABA",
        description="Ciudad Autónoma de Buenos Aires",
        status="Active",
        district=District.objects.get(name="CABA")
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0008_auto_20160616_1201'),
    ]

    operations = [
        migrations.RunPython(loadLocation),
    ]
