# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'Initial', b'Inicial'), (b'Sent', b'Enviada'), (b'Error', b'Error')], default=b'Initial', max_length=10)),
                ('notificationtype', models.CharField(choices=[(b'SMS', b'SMS'), (b'Email', b'Email')], max_length=10)),
                ('destination', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_notificaciones.BaseNotification')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_notificaciones.basenotification',),
        ),
        migrations.CreateModel(
            name='NotificationSMS',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_notificaciones.BaseNotification')),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_notificaciones.basenotification',),
        ),
    ]
