# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
        ('hc_pacientes', '0002_initial_data'),
        ('hc_notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='hc_practicas.Turno'),
        ),
    ]
