# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
