# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_notificaciones', '0002_auto_20161104_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='message',
            field=models.CharField(max_length=10000),
        ),
    ]
