# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
        ('hc_notificaciones', '0002_auto_20170131_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotificationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsetype', models.CharField(choices=[(b'SMS', b'SMS'), (b'Email', b'Email')], max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Turno'),
        ),
        migrations.CreateModel(
            name='SMSNotificationResponse',
            fields=[
                ('basenotificationresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_notificaciones.BaseNotificationResponse')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='hc_notificaciones.NotificationSMS')),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_notificaciones.basenotificationresponse',),
        ),
        migrations.AddField(
            model_name='basenotificationresponse',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='basenotificationresponse',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_practicas.Turno'),
        ),
    ]
