# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_notificaciones', '0003_auto_20170203_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotificationresponse',
            name='responseaction',
            field=models.CharField(choices=[(b'Cancel', b'Cancel'), (b'SendOptions', b'SendOptions')], default='Resend', max_length=15),
            preserve_default=False,
        ),
    ]
