# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allDay', models.BooleanField()),
                ('availableStartTime', models.TimeField()),
                ('availableEndTime', models.TimeField()),
                ('daysOfWeek', models.ManyToManyField(to='common.DayOfWeek')),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.TextField()),
                ('location', models.TextField()),
                ('serviceName', models.TextField()),
                ('comment', models.TextField()),
                ('extraDetails', models.TextField()),
                ('photo', models.TextField()),
                ('converageArea', models.TextField()),
                ('serviceProvisioningCode', models.TextField()),
                ('eligibility', models.TextField()),
                ('eligibilityNote', models.TextField()),
                ('programName', models.TextField()),
                ('characteristic', models.TextField()),
                ('referralMethod', models.TextField()),
                ('publicKey', models.TextField()),
                ('appointmentRequired', models.BooleanField()),
                ('notAvailable', models.TextField()),
                ('availabilityExceptions', models.TextField()),
                ('availableTime', models.ManyToManyField(to='practicioners.AvailableTime')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Identifier')),
                ('providedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Organization')),
            ],
            options={
                'ordering': ['serviceName'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Coding')),
            ],
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='serviceCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicioners.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='telecom',
            field=models.ManyToManyField(to='common.ContactPoint'),
        ),
    ]
